image: google/cloud-sdk:alpine

services:
  - docker:dind

variables:
  SERVICE_NAME_API: flight-api
  SERVICE_NAME_UI: flight-ui
  DOCKER_DRIVER: overlay2
  # us-central1-docker.pkg.dev/flight-cancellation-prediction/flight
  REGISTRY_IMAGE_API: us-central1-docker.pkg.dev/flight-cancellation-prediction/flight/my_app
  VERSION_API: 0.1
  REGISTRY_IMAGE_UI: us-central1-docker.pkg.dev/flight-cancellation-prediction/flight/my_gradio
  VERSION_UI: 0.1
  ZONE: europe-west3-a 
  CLUSTER_NAME: flight-cancellation-k8s

stages:
  - test

test:
  stage: test
  script:
    - cp $GCP_SERVICE_ACCOUNT_KEY /tmp/keyfile.json
    - gcloud auth activate-service-account --key-file=/tmp/keyfile.json
    - gcloud config set project $CI_PROJECT_ID
    - >
      gcloud builds submit
      --config=cloudbuild.yaml
      --substitutions=_REGISTRY_IMAGE_API=$REGISTRY_IMAGE_API,_VERSION_API=$VERSION_API,_REGISTRY_IMAGE_UI=$REGISTRY_IMAGE_UI,_VERSION_UI=$VERSION_UI,_SERVICE_NAME_API=$SERVICE_NAME_API,_SERVICE_NAME_UI=$SERVICE_NAME_UI,_CLUSTER_NAME=$CLUSTER_NAME,_ZONE=$ZONE,_PROJECT_ID=$CI_PROJECT_ID

      .

  only:
    - main
# --substitutions=_REGISTRY_IMAGE_API=$REGISTRY_IMAGE_API,_VERSION_API=$VERSION_API,_REGISTRY_IMAGE_UI=$REGISTRY_IMAGE_UI,_VERSION_UI=$VERSION_UI,_SERVICE_NAME_API=$SERVICE_NAME_API,_SERVICE_NAME_UI=$SERVICE_NAME_UI

