image: google/cloud-sdk:alpine

# services:
#   - docker:dind

variables:
  SERVICE_NAME_API: flight-api
  SERVICE_NAME_UI: flight-ui
  DOCKER_DRIVER: overlay2
  # us-central1-docker.pkg.dev/flight-cancellation-prediction/flight
  REGISTRY_IMAGE_API: europe-west4-docker.pkg.dev/flight-cancellation-pred/flight/my_app
  VERSION_API: 0.15
  REGISTRY_IMAGE_UI: europe-west4-docker.pkg.dev/flight-cancellation-pred/flight/my_streamlit
  VERSION_UI: 0.15
  ZONE: europe-west4-a 
  CLUSTER_NAME: flight-k8s
  PROJECT_NAME: flight
  NAMESPACE: prod

stages:
  - test

test:
  stage: test
  script:
    - cp $GCP_SERVICE_ACCOUNT_KEY3 /tmp/keyfile.json
    - gcloud auth activate-service-account --key-file=/tmp/keyfile.json
    - echo "CI_PROJECT_ID variable value $CI_PROJECT_ID"
    - gcloud config set project $CI_PROJECT_ID
    - >
      gcloud builds submit
      --config=cloudbuild.yaml
      --substitutions=_REGISTRY_IMAGE_API=$REGISTRY_IMAGE_API,_VERSION_API=$VERSION_API,_REGISTRY_IMAGE_UI=$REGISTRY_IMAGE_UI,_VERSION_UI=$VERSION_UI,_SERVICE_NAME_API=$SERVICE_NAME_API,_SERVICE_NAME_UI=$SERVICE_NAME_UI .


  only:
    - main

# for k8s: --substitutions=_REGISTRY_IMAGE_API=$REGISTRY_IMAGE_API,_VERSION_API=$VERSION_API,_REGISTRY_IMAGE_UI=$REGISTRY_IMAGE_UI,_VERSION_UI=$VERSION_UI,_CLUSTER_NAME=$CLUSTER_NAME,_ZONE=$ZONE,_PROJECT_ID=$CI_PROJECT_ID,_PROJECT_NAME=$PROJECT_NAME,_NAMESPACE=$NAMESPACE .


