# Dry-run configuration for Flight Cancellation Prediction
data:
  dataset: "flights"
  table: "flights_all"
  limit: 100000        
  target_column: "Cancelled"
  date_column: "FlightDate"
  columns_to_drop_id: "columns_to_drop_id.txt"
  columns_to_drop_high_correlation: "columns_to_drop_high_correlation.txt"
  columns_to_drop_leakage: "columns_to_drop_leakage.txt"
  post_event_columns: []

models:
  - "xgboost"
  - "lightgbm"
  - "catboost"

preprocessing:
  impute_missing: false

optimization:
  n_trials: 2                   # just two Optuna trials
  cv_folds: 2                   # two-fold CV
  beta: 0.25

mlflow:
  tracking_uri: "./mlruns"
  experiment_name: "Flight_Cancellation_Prediction_DryRun"

hyperparameters:
  xgboost:
    optimize:
      max_depth:
        min: 3
        max: 6
      learning_rate:
        min: 0.05
        max: 0.2
      n_estimators:
        min: 50
        max: 200
    fixed:
      min_child_weight: 1
      gamma: 0.0
      subsample: 1.0
      colsample_bytree: 1.0

  lightgbm:
    optimize:
      num_leaves:
        min: 20
        max: 50
      learning_rate:
        min: 0.1
        max: 0.2
      n_estimators:
        min: 50
        max: 200
    fixed:
      min_child_samples: 20
      subsample: 1.0
      colsample_bytree: 1.0
      reg_alpha: 0.1
      reg_lambda: 0.1

  catboost:
    optimize:
      depth:
        min: 4
        max: 6
      learning_rate:
        min: 0.01
        max: 0.2
      iterations:
        min: 50
        max: 200
    fixed:
      l2_leaf_reg: 3.0
      bagging_temperature: 1.0
      random_strength: 1.0
