version: "3.9"
services:
  api-flight:  
    build: my_app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/bq.json
      - GCP_PROJECT_ID=flight-cancellation-pred
    volumes:
      - /home/sevas1saves/.keys/flight-cancellation-pred_bq.json:/secrets/bq.json:ro
    ports:
      - 8006:8001
    container_name: flight_api
  
  ui:
    build: my_gradio
    ports:
      - 8005:8005
    container_name: gradio_ui
    depends_on:
      - api-flight 
  
  streamlit:
    build: my_streamlit
    ports:
      - 8501:8501
    container_name: streamlit_ui
    depends_on:
      - api-flight
