apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-__PROJECT_NAME__
  labels:
    app: ui-__PROJECT_NAME__
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-__PROJECT_NAME__
  template:
    metadata:
      labels:
        app: ui-__PROJECT_NAME__
        version: v1
    spec:
      containers:
        - name: ui-__PROJECT_NAME__
          image: __UI__VERSION__
          ports:
            - containerPort: 8005
              protocol: TCP
          resources:
            limits:
              cpu: 0.2
              memory: 512Mi
            requests:
              cpu: 0.1
              memory: 256Mi
          # Health checks для UI
          livenessProbe:
            httpGet:
              path: /
              port: 8005
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ui-__PROJECT_NAME__
  annotations:
    cloud.google.com/load-balancer-type: "External"
    # Опционально: использовать статический IP
    # cloud.google.com/load-balancer-ip: "YOUR-STATIC-IP"
spec:
  selector:
    app: ui-__PROJECT_NAME__
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8005
      protocol: TCP
  sessionAffinity: ClientIP
