apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: prod
  annotations:
    iam.gke.io/gcp-service-account: flight-bq-sa@flight-cancellation-prediction.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-flight
  namespace: prod
  labels:
    app: api-flight
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-flight
  template:
    metadata:
      labels:
        app: api-flight
        version: v1
    spec:
      serviceAccountName: api-sa
      containers:
        - name: api
          image: gcr.io/flight-cancellation-prediction/flight-api:latest
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: BQ_PROJECT
              value: "flight-cancellation-prediction"
            - name: BQ_DATASET
              value: "mlflow_tracking"
            - name: BQ_LOCATION
              value: "EU"  # or europe-west3 (must match your dataset)
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "200m", memory: "512Mi" }
          livenessProbe:
            httpGet: { path: /health, port: 8001 }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet: { path: /health, port: 8001 }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: api-flight
  namespace: prod
spec:
  selector:
    app: api-flight
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8001
      protocol: TCP
  sessionAffinity: ClientIP
