apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-flight
  namespace: prod
  labels:
    app: ui-flight
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-flight
  template:
    metadata:
      labels:
        app: ui-flight
        version: v1
    spec:
      containers:
        - name: ui
          image: __API__VERSION__          
          ports:
            - containerPort: 8005
              protocol: TCP
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "200m", memory: "512Mi" }
          livenessProbe:
            httpGet: { path: /, port: 8005 }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet: { path: /, port: 8005 }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: ui-flight
  namespace: prod
spec:
  selector:
    app: ui-flight
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8005
      protocol: TCP
  sessionAffinity: ClientIP
