apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-__PROJECT_NAME__
  labels:
    app: api-__PROJECT_NAME__
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-__PROJECT_NAME__
  template:
    metadata:
      labels:
        app: api-__PROJECT_NAME__
        version: v1
    spec:
      containers:
        - name: api-__PROJECT_NAME__
          image: __API__VERSION__
          ports:
            - containerPort: 8001
              protocol: TCP
          resources:
            limits:
              cpu: 0.2
              memory: 512Mi
            requests:
              cpu: 0.1
              memory: 256Mi
          # Добавляем health checks для LoadBalancer
          livenessProbe:
            httpGet:
              path: /health  # Измените на ваш endpoint
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health  # Измените на ваш endpoint
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-__PROJECT_NAME__
  annotations:
    # Для GKE LoadBalancer
    cloud.google.com/load-balancer-type: "External"
    # Опционально: использовать статический IP (нужно предварительно создать)
    # cloud.google.com/load-balancer-ip: "YOUR-STATIC-IP"
spec:
  selector:
    app: api-__PROJECT_NAME__
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8001
      protocol: TCP
  # Добавляем sessionAffinity для стабильности
  sessionAffinity: ClientIP
