project:
  name: flight_cancellation_pred
  dataset: flight_data
  table: combined_flights
  sample_size: 10000

# flight-cancellation-pred.mlflow_tracking.mlflow_metrics_log
bq_logging:
  target_table: mlflow_metrics_log
  dataset: mlflow_tracking
  gcs_bucket: mlflow_flight_cancellation

output_path:
  results/

optuna:
  study_name: fly1
  storage_path: results/fly1.db
  n_trials: 3

cross_validation:
  nfolds: 2
mlflow:
  experiment_name: flight_cancellation_prediction
  model_name: flight_cancellation_model

data:
  describe_csv_path: results/flights_all_analysis_with_roles.csv
  roles_output_path: results/training_taken_roles.json

columns:
  target: Cancelled
  skip_additional:
    - DivAirportLandings
    - DepartureDelayGroups
    - AirTime
    - ArrivalDelayGroups
    - ArrDelay
    - ArrDelayMinutes
    - DepDelay
    - DepDelayMinutes
    - ActualElapsedTime
    - TaxiOut
    - TaxiIn
    - Diverted
    - __index_level_0__
    - DepDel15
    - ArrDel15
